# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''

np.random.seed(1)
#定義一個 4x4x3 的 feature map
a_slice_prev = np.arange(4*4*3).reshape(4,4,3)
W = np.random.randn(4, 4, 3)
b = np.ones((1, 1, 1))

#取得計算後,卷績矩陣的值
Z = conv_single_step(a_slice_prev, W, b)

In [4]:
a_slice_prev

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]]])

In [5]:
print(W)
b

[[[ 1.62434536 -0.61175641 -0.52817175]
  [-1.07296862  0.86540763 -2.3015387 ]
  [ 1.74481176 -0.7612069   0.3190391 ]
  [-0.24937038  1.46210794 -2.06014071]]

 [[-0.3224172  -0.38405435  1.13376944]
  [-1.09989127 -0.17242821 -0.87785842]
  [ 0.04221375  0.58281521 -1.10061918]
  [ 1.14472371  0.90159072  0.50249434]]

 [[ 0.90085595 -0.68372786 -0.12289023]
  [-0.93576943 -0.26788808  0.53035547]
  [-0.69166075 -0.39675353 -0.6871727 ]
  [-0.84520564 -0.67124613 -0.0126646 ]]

 [[-1.11731035  0.2344157   1.65980218]
  [ 0.74204416 -0.19183555 -0.88762896]
  [-0.74715829  1.6924546   0.05080775]
  [-0.63699565  0.19091548  2.10025514]]]


array([[[1.]]])

In [6]:
a_slice_prev*W+b

array([[[ 1.00000000e+00,  3.88243586e-01, -5.63435045e-02],
        [-2.21890587e+00,  4.46163052e+00, -1.05076935e+01],
        [ 1.14688706e+01, -4.32844831e+00,  3.55231277e+00],
        [-1.24433338e+00,  1.56210794e+01, -2.16615478e+01]],

       [[-2.86900645e+00, -3.99270661e+00,  1.68727722e+01],
        [-1.54983690e+01, -1.75885132e+00, -1.39235931e+01],
        [ 1.75984744e+00,  1.20734891e+01, -2.10123835e+01],
        [ 2.50391979e+01,  2.08349959e+01,  1.25573698e+01]],

       [[ 2.26205428e+01, -1.60931965e+01, -2.19514586e+00],
        [-2.42657747e+01, -6.50086623e+00,  1.63803085e+01],
        [-1.97498226e+01, -1.12993593e+01, -2.09895264e+01],
        [-2.68917862e+01, -2.18223684e+01,  5.56739038e-01]],

       [[-3.92231726e+01,  9.67338082e+00,  6.40724827e+01],
        [ 2.99397223e+01, -6.67342209e+00, -3.53927875e+01],
        [-3.03806483e+01,  7.37755478e+01,  3.23554121e+00],
        [-2.76648041e+01,  9.78211229e+00,  9.97119914e+01]]])

In [8]:
Z

20.163314814419635