## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.datasets import load_boston
# type(boston.data) #numpy.ndarray
# boston.data.shape #(506, 13)

In [2]:
# 讀取資料集
boston = load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

print(y_test[:5])
print(y_pred[:5])


[16.5 24.8 17.4 19.3 37.6]
[12.07495986 26.9894969  17.58803353 18.15584511 36.92091659]


In [3]:
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [4]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

Mean squared error: 25.42
r2_score: 0.73


In [5]:
# 讀取資料集
boston = load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型  lasso
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [6]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [7]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

Mean squared error: 28.95
r2_score: 0.69


In [8]:
#drop lasso coeff=0 columns再做一次回歸
lasso_coeff0=np.where(lasso.coef_==0)
#(array([2, 3, 4], dtype=int64),)
lasso_coeff_keep_col=np.setxor1d(range(len(lasso.coef_)),lasso_coeff0)
#array([ 0,  1,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)


# 讀取資料集
boston = load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data[:,lasso_coeff_keep_col], boston.target, test_size=0.2, random_state=4)
#                                                   -----------------------------------   

#### 特徵選取去掉係數為0者從跑Lasso回歸
# 建立一個線性回歸模型  lasso
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)



In [9]:
lasso.coef_

array([-0.064947  ,  0.04581424,  1.18140916,  0.01109107, -0.73695757,
        0.23348792, -0.01551016, -0.69270451,  0.00763151, -0.69278585])

In [10]:
print('特徵選取去掉係數為0者從跑Lasso回歸')
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

特徵選取去掉係數為0者從跑Lasso回歸
Mean squared error: 28.95
r2_score: 0.69


In [11]:
# 特徵選取去掉係數為0者從跑Linear回歸

regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [12]:
print(regr.coef_)

[-0.11222109  0.05061586  4.19670387 -0.02504823 -1.26271144  0.28485104
 -0.01693221 -0.77398518  0.01018528 -0.48227497]


In [13]:
print('特徵選取去掉係數為0者從跑Linear回歸')
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

特徵選取去掉係數為0者從跑Linear回歸
Mean squared error: 26.74
r2_score: 0.71


In [20]:
# 讀取資料集
boston = load_boston()
boston.data.shape
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

In [22]:
print('ridge regression')
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

ridge regression
Mean squared error: 25.74
r2_score: 0.72


In [39]:
# 讀取資料集
boston = load_boston()
boston.data.shape
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=0.1)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

print('ridge regression')
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print("r2_score: %.2f"%r2_score(y_test, y_pred))

ridge regression
Mean squared error: 25.46
r2_score: 0.73


可以看見 LASSO 與 Ridge 的結果並沒有比原本的線性回歸來得好， 這是因為目標函數被加上了正規化函數，讓模型不能過於複雜，相當於限制模型擬和資料的能力。因此若沒有發現 Over-fitting 的情況，是可以不需要一開始就加上太強的正規化的。
以Lasso特徵選取後保留之係數再做一次LinearRegression，效果也沒原先好